/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Quarkus PrimeReact Monorepo
 * Quarkus monorepo demonstrating Panache REST server with PrimeReact UI client
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';

export const carVinMax = 17;

export const carVinRegExp = new RegExp('\\S');
export const carMakeMax = 255;

export const carMakeRegExp = new RegExp('\\S');
export const carModelMax = 255;

export const carModelRegExp = new RegExp('\\S');
export const carYearMin = 1960;
export const carYearMax = 2050;

export const carColorMax = 20;

export const carColorRegExp = new RegExp('\\S');
export const carPriceMin = 0;
export const carPriceMax = 250000;

export const Car = zod
	.object({
		id: zod.coerce.number().optional(),
		vin: zod.coerce.string().max(carVinMax).regex(carVinRegExp).describe('VIN number'),
		make: zod.coerce.string().max(carMakeMax).regex(carMakeRegExp).describe('Manufacturer'),
		model: zod.coerce.string().max(carModelMax).regex(carModelRegExp).describe('Model Number'),
		year: zod.coerce.number().min(carYearMin).max(carYearMax).describe('Year of manufacture'),
		color: zod.coerce.string().max(carColorMax).regex(carColorRegExp).describe('HTML color of the car'),
		price: zod.coerce.number().min(carPriceMin).max(carPriceMax).describe('Price'),
		modifiedTime: zod.coerce.date().optional().describe('Modified time of the record')
	})
	.describe('Entity that represents a car.');

export type Car = zod.input<typeof Car>;
export type CarOutput = zod.output<typeof Car>;

export const FilterConstraint = zod.object({
	value: zod.unknown().optional().describe('Value to filter this column by'),
	matchMode: zod.coerce.string().optional().describe('Filter match mode e.g. equals, notEquals, contains, notContains, gt, gte, lt, lte')
});

export type FilterConstraint = zod.input<typeof FilterConstraint>;
export type FilterConstraintOutput = zod.output<typeof FilterConstraint>;

export const HttpProblem = zod
	.object({
		type: zod.url().optional().describe('A optional URI reference that identifies the problem type'),
		title: zod.coerce.string().optional().describe('A optional, short, human-readable summary of the problem type'),
		status: zod.coerce.number().optional().describe('The HTTP status code for this occurrence of the problem'),
		detail: zod.coerce.string().optional().describe('A optional human-readable explanation specific to this occurrence of the problem'),
		instance: zod.url().optional().describe('A URI reference that identifies the specific occurrence of the problem')
	})
	.describe('HTTP Problem Response according to RFC9457 and RFC7807');

export type HttpProblem = zod.input<typeof HttpProblem>;
export type HttpProblemOutput = zod.output<typeof HttpProblem>;

export const Violation = zod
	.object({
		field: zod.coerce.string().optional().describe('The field for which the validation failed'),
		in: zod.coerce.string().optional().describe('Part of the http request where the validation error occurred such as query, path, header, form, body'),
		message: zod.coerce.string().optional().describe('Description of the validation error')
	})
	.describe('Validation constraint violation details');

export type Violation = zod.input<typeof Violation>;
export type ViolationOutput = zod.output<typeof Violation>;

export const HttpValidationProblem = zod
	.object({
		type: zod.url().optional().describe('A optional URI reference that identifies the problem type'),
		title: zod.coerce.string().optional().describe('A optional, short, human-readable summary of the problem type'),
		status: zod.coerce.number().optional().describe('The HTTP status code for this occurrence of the problem'),
		detail: zod.coerce.string().optional().describe('A optional human-readable explanation specific to this occurrence of the problem'),
		instance: zod.url().optional().describe('A URI reference that identifies the specific occurrence of the problem'),
		violations: zod.array(Violation).optional().describe('List of validation constraint violations that occurred')
	})
	.describe('HTTP Validation Problem Response according to RFC9457 and RFC7807');

export type HttpValidationProblem = zod.input<typeof HttpValidationProblem>;
export type HttpValidationProblemOutput = zod.output<typeof HttpValidationProblem>;

export const Instant = zod.coerce.date();

export type Instant = zod.input<typeof Instant>;
export type InstantOutput = zod.output<typeof Instant>;

export const MultiFilterMeta = zod.object({
	value: zod.unknown().optional().describe('Value to filter this column by'),
	matchMode: zod.coerce.string().optional().describe('Filter match mode e.g. equals, notEquals, contains, notContains, gt, gte, lt, lte'),
	operator: zod.coerce.string().optional().describe("Filter operator either 'and' or 'or'"),
	constraints: zod.array(FilterConstraint).optional().describe('List of filter constraints for this filter')
});

export type MultiFilterMeta = zod.input<typeof MultiFilterMeta>;
export type MultiFilterMetaOutput = zod.output<typeof MultiFilterMeta>;

export const MultiSortMeta = zod.object({
	field: zod.coerce.string().optional().describe('Sort field for this multiple sort'),
	order: zod.coerce.number().optional().describe('Sort order for this field either -1 desc, 0 none, 1 asc')
});

export type MultiSortMeta = zod.input<typeof MultiSortMeta>;
export type MultiSortMetaOutput = zod.output<typeof MultiSortMeta>;

export const QueryRequest = zod
	.object({
		first: zod.coerce.number().optional().describe('First record'),
		rows: zod.coerce.number().optional().describe('Number of rows'),
		page: zod.coerce.number().optional().describe('Page number'),
		sortField: zod.coerce.string().optional().describe('Sort field if single field sorting'),
		sortOrder: zod.coerce.number().optional().describe('Sort order if single field sorting either -1 desc, 0 none, 1 asc'),
		multiSortMeta: zod.array(MultiSortMeta).optional().describe('Multiple sorting list of columns to sort and in which order'),
		filters: zod.record(zod.string(), MultiFilterMeta).optional().describe('Map of columns being filtered and their filter criteria')
	})
	.describe('Represents a PrimeReact query request from the UI for a complex datatable with multiple sorts, multiple filters, and pagination.');

export type QueryRequest = zod.input<typeof QueryRequest>;
export type QueryRequestOutput = zod.output<typeof QueryRequest>;

export const QueryResponse = zod
	.object({
		totalRecords: zod.coerce.number().optional().describe('Total records available by this query criteria'),
		records: zod.array(zod.unknown()).optional().describe('Records for this set of pagination, sorting, filtering.')
	})
	.describe('Represents a PrimeReact query response to the UI for a complex datatable with multiple sorts, multiple filters, and pagination.');

export type QueryResponse = zod.input<typeof QueryResponse>;
export type QueryResponseOutput = zod.output<typeof QueryResponse>;

export const QueryResponseCar = zod
	.object({
		totalRecords: zod.coerce.number().optional().describe('Total records available by this query criteria'),
		records: zod.array(Car).optional().describe('Records for this set of pagination, sorting, filtering.')
	})
	.describe('Represents a PrimeReact query response to the UI for a complex datatable with multiple sorts, multiple filters, and pagination.');

export type QueryResponseCar = zod.input<typeof QueryResponseCar>;
export type QueryResponseCarOutput = zod.output<typeof QueryResponseCar>;

export const SocketMessage = zod
	.object({
		id: zod.coerce.string().optional().describe('Unique identifier for the message'),
		timestamp: zod.coerce.date().optional().describe('UTC timestamp of when the message was created'),
		type: zod.enum(['REFRESH_DATA', 'NOTIFICATION']).describe('Type of socket message'),
		message: zod.coerce.string().optional().describe('Optional message payload'),
		context: zod.record(zod.string(), zod.coerce.string()).optional().describe('Additional context information for the message')
	})
	.describe('WebSocket message for real-time updates');

export type SocketMessage = zod.input<typeof SocketMessage>;
export type SocketMessageOutput = zod.output<typeof SocketMessage>;

export const SocketMessageType = zod.enum(['REFRESH_DATA', 'NOTIFICATION']);

export type SocketMessageType = zod.input<typeof SocketMessageType>;
export type SocketMessageTypeOutput = zod.output<typeof SocketMessageType>;

export const ZonedDateTime = zod.coerce.date();

export type ZonedDateTime = zod.input<typeof ZonedDateTime>;
export type ZonedDateTimeOutput = zod.output<typeof ZonedDateTime>;

export const LoggerLevel = zod.enum([
	'OFF',
	'SEVERE',
	'ERROR',
	'FATAL',
	'WARNING',
	'WARN',
	'INFO',
	'DEBUG',
	'TRACE',
	'CONFIG',
	'FINE',
	'FINER',
	'FINEST',
	'ALL'
]);

export type LoggerLevel = zod.input<typeof LoggerLevel>;
export type LoggerLevelOutput = zod.output<typeof LoggerLevel>;

export const LoggerInfo = zod.object({
	configuredLevel: LoggerLevel.optional(),
	effectiveLevel: LoggerLevel.optional(),
	name: zod.coerce.string().optional()
});

export type LoggerInfo = zod.input<typeof LoggerInfo>;
export type LoggerInfoOutput = zod.output<typeof LoggerInfo>;

export const HealthCheck = zod.object({
	data: zod.looseObject({}).nullish(),
	name: zod.coerce.string().optional(),
	status: zod.enum(['UP', 'DOWN']).optional()
});

export type HealthCheck = zod.input<typeof HealthCheck>;
export type HealthCheckOutput = zod.output<typeof HealthCheck>;

export const HealthResponse = zod.object({
	checks: zod.array(HealthCheck).optional(),
	status: zod.enum(['UP', 'DOWN']).optional()
});

export type HealthResponse = zod.input<typeof HealthResponse>;
export type HealthResponseOutput = zod.output<typeof HealthResponse>;
/**
 * Returns a paginated list of cars with optional filtering and sorting
 * @summary List cars
 */
export const GetEntityCarsQueryParams = zod.object({
	request: zod.coerce.string().optional()
});

export const GetEntityCarsResponse = QueryResponseCar;

/**
 * Creates a new car entry
 * @summary Create a new car
 */
export const PostEntityCarsBody = Car;

export const PostEntityCarsResponse = Car;

/**
 * Returns a list of distinct car manufacturers
 * @summary Get all manufacturers
 */
export const GetEntityCarsManufacturersResponseItem = zod.coerce.string();
export const GetEntityCarsManufacturersResponse = zod.array(GetEntityCarsManufacturersResponseItem);

/**
 * Updates an existing car based on ID
 * @summary Update a car
 */
export const putEntityCarsIdPathIdMin = 0;

export const PutEntityCarsIdParams = zod.object({
	id: zod.coerce.number().min(putEntityCarsIdPathIdMin)
});

export const PutEntityCarsIdBody = Car;

export const PutEntityCarsIdResponse = Car;

/**
 * Returns a car based on the provided ID
 * @summary Get a car by ID
 */
export const getEntityCarsIdPathIdMin = 0;

export const GetEntityCarsIdParams = zod.object({
	id: zod.coerce.number().min(getEntityCarsIdPathIdMin)
});

export const GetEntityCarsIdResponse = Car;

/**
 * Deletes a car based on ID
 * @summary Delete a car
 */
export const deleteEntityCarsIdPathIdMin = 0;

export const DeleteEntityCarsIdParams = zod.object({
	id: zod.coerce.number().min(deleteEntityCarsIdPathIdMin)
});

export const DeleteEntityCarsIdResponse = zod.void();

/**
 * Pushes a notification message to all connected clients
 * @summary Push notification message
 */
export const PostSocketNotifyQueryParams = zod.object({
	message: zod.coerce.string().optional()
});

export const PostSocketNotifyResponse = zod.void();

/**
 * Pushes a UI refresh signal to all connected clients
 * @summary Push a UI refresh signal
 */
export const PostSocketRefreshResponse = zod.void();

/**
 * Get information on all loggers or a specific logger.
 * @summary Information on Logger(s)
 */
export const LoggingManagerGetAllQueryParams = zod.object({
	loggerName: zod.coerce.string().optional()
});

export const LoggingManagerGetAllResponseItem = LoggerInfo;
export const LoggingManagerGetAllResponse = zod.array(LoggingManagerGetAllResponseItem);

/**
 * Update a log level for a certain logger. Use query param `temporary=true` for temporary level.
 * @summary Update log level
 */
export const LoggingManagerUpdateQueryParams = zod.object({
	temporary: zod.coerce.boolean().optional().describe('Used to set the log level temporarily')
});

export const LoggingManagerUpdateResponse = zod.unknown();

/**
 * This returns all possible log levels
 * @summary Get all available levels
 */
export const LoggingManagerLevelsResponseItem = LoggerLevel;
export const LoggingManagerLevelsResponse = zod.array(LoggingManagerLevelsResponseItem);

/**
 * Check the health of the application
 * @summary An aggregated view of the Liveness, Readiness and Startup of this application
 */
export const MicroprofileHealthRootResponse = HealthResponse;

/**
 * Check the liveness of the application
 * @summary The Liveness check of this application
 */
export const MicroprofileHealthLivenessResponse = HealthResponse;

/**
 * Check the readiness of the application
 * @summary The Readiness check of this application
 */
export const MicroprofileHealthReadinessResponse = HealthResponse;

/**
 * Check the startup of the application
 * @summary The Startup check of this application
 */
export const MicroprofileHealthStartupResponse = HealthResponse;
